### PR TITLE
Importing mouse from 'd3' module, removing 'arguments'

### PR DESCRIPTION
**Pull request by dyuri**
It seems I've found the solution for the mouse issue, it should be imported from `d3` instead of `d3-selection` and then it works (for me). (See #5 )
I've also replaced the `arguments.length` check in `options.js` since `arguments` is not available inside arrow functions.

### CODE REVIEW

**Comment by BigFatDog** [comment]
Hello @dyuri ,

Thanks for submitting this PR. 
1. Do your modifications on `apiGraphite.js` resolve another problem? If so please submit those  changes separately in another PR. We'd discuss on it, then.
2. Adding `d3` as dependency would significantly increase the bundle size of `cubism-es`.

Now I have a very simple solution, we can use `d3.mouse` without neither modification to source code  nor bundling structure: adding `d3` as `peerDependency`.

Yours 
Yun

**Comment by dyuri** [comment]
Ah, sorry, I didn't mean to submit all these changes (I submitted the PR 17 days ago, and these changes are much more recent, and far from ready yet).
The bundle size should be only slightly bigger, we do not include the whole `d3` module, only the exported `mouse` object.
I checked the bundle sizes, original:
```
51902 dist/cubism-es.esm.js
55468 dist/cubism-es.js
```
With `import {mouse} from 'd3'`:
```
51927 dist/cubism-es.esm.js
55508 dist/cubism-es.js
```
That's not that much.

**Comment by dyuri** [comment]
Anyway, sorry about the other changeset, I'm going to close this PR, and if you have an other solution, it's fine for me as well.

**Comment by BigFatDog** [comment]
Sure, I'll check it out this week and keep you updated here.

**Comment by BigFatDog** [comment]
Version `1.1.2` has been released to address this issue.
I've tested in a react application without declaring `d3` as globals using `webpack ProvidePlugin`.

`readme` has been revised to explain the usage into details.

If it still doesn't work in your environment, I'd make `cubism-es` depend on `d3` directly, since you've already tested the bundle size is fine. (I'll dig into the bundle size myself afterwards on my own interest. In this case `tree shaking` is disabled and bundle size should increase a lot. According to your observation, it could be either `tree shaking still works, or the bundled d3 code itself is small in size)

**Comment by dyuri** [comment]
Thanks, latest version works fine for me.

**Comment by BigFatDog** [comment]
That's good! Thanks again for your time on this PR. Have a good day!

**Pull request closed without merging**
